version: '3.3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always

  broker:
    image: wurstmeister/kafka
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: broker
      KAFKA_CREATE_TOPICS: "http_available_job:24:1,exploit_results:24:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: always

  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"

  worker:
    image:

  web:
    image:

  kafka_to_db:
    image:
